// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TacoLoco.DBContexts;

namespace TacoLoco.Migrations
{
    [DbContext(typeof(TacoLocoDeliveryContext))]
    partial class TacoLocoDeliveryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TacoLoco.Entities.TacoLocoDelivery", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeliveryStatus")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ZipCode")
                        .HasColumnType("bigint");

                    b.HasKey("DeliveryId");

                    b.ToTable("TacoLocoDelivery");

                    b.HasData(
                        new
                        {
                            DeliveryId = 1,
                            City = "Canton",
                            DeliveryStatus = 0,
                            FirstName = "Shivani",
                            LastName = "Vyas",
                            PhoneNumber = "1234567890",
                            State = "Michigan",
                            StreetAddress1 = "Canton",
                            StreetAddress2 = "",
                            ZipCode = 48188L
                        },
                        new
                        {
                            DeliveryId = 2,
                            City = "Detroit",
                            DeliveryStatus = 1,
                            FirstName = "Bob",
                            LastName = "Arnold",
                            PhoneNumber = "1568217890",
                            State = "Michigan",
                            StreetAddress1 = "Lauree Ville Dr",
                            StreetAddress2 = "House Number 1103",
                            ZipCode = 48100L
                        },
                        new
                        {
                            DeliveryId = 3,
                            City = "Canton",
                            DeliveryStatus = 2,
                            FirstName = "John",
                            LastName = "Smith",
                            PhoneNumber = "1234567890",
                            State = "Michigan",
                            StreetAddress1 = "Queens Ln",
                            StreetAddress2 = "Apt Honeycomb Circle, 1212",
                            ZipCode = 48188L
                        },
                        new
                        {
                            DeliveryId = 4,
                            City = "Los Angeles",
                            DeliveryStatus = 2,
                            FirstName = "Steve",
                            LastName = "Jobs",
                            PhoneNumber = "9997845896",
                            State = "California",
                            StreetAddress1 = "McLumpha Dr",
                            StreetAddress2 = "House # 1001",
                            ZipCode = 57814L
                        },
                        new
                        {
                            DeliveryId = 5,
                            City = "San Francisco",
                            DeliveryStatus = 1,
                            FirstName = "Bill",
                            LastName = "Gates",
                            PhoneNumber = "8833052351",
                            State = "California",
                            StreetAddress1 = "Mountain View Ln",
                            StreetAddress2 = "House # 007",
                            ZipCode = 415205L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
